---
abstract: 'InternetSecure backend for Business::OnlinePayment'
author:
  - 'Frédéric Brière <fbriere@fbriere.net>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.120921'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Business-OnlinePayment-InternetSecure
no_index:
  directory:
    - t
    - inc
requires:
  Business::OnlinePayment: 2
  Net::SSLeay: 0
  XML::Simple: 0
version: 0.06
